// ============================================================
// FILE: lib/core/localization/ar_ae.dart
// ============================================================

const Map<String, String> arAe = {
  // App
  'app_name': 'شركة ABC للتجارة',
  'hello': 'مرحباً',
  'welcome_back':           'مرحباً بعودتك',
  'login_subtitle':         'تسجيل الدخول لإدارة أعمالك',
  'register_subtitle':      'أنشئ حساب عملك',
  'email':                  'البريد الإلكتروني',
  'email_hint':             'your@business.com',
  'password':               'كلمة المرور',
  'password_hint':          '٦ أحرف على الأقل',
  'confirm_password':       'تأكيد كلمة المرور',
  'confirm_password_hint':  'أعد إدخال كلمة المرور',
  'login':                  'تسجيل الدخول',
  'register':               'إنشاء حساب',
  'create_account':         'إنشاء حساب',
  'or':                     'أو',
  'business_info':          'معلومات العمل',
  'business_name':          'اسم العمل',
  'business_name_hint':     'مثال: متجر أحمد العام',
  'owner_name':             'اسم المالك',
  'owner_name_hint':        'اسمك الكامل',
  'contact_info':           'معلومات الاتصال',
  'phone':                  'رقم الهاتف',
  'phone_hint':             '+971 50 000 0000',
  'security':               'الأمان',
  'business_name_required': 'اسم العمل مطلوب',
  'valid_email_required':   'أدخل بريد إلكتروني صحيح',
  'password_required':      'كلمة المرور مطلوبة',
  'password_min_6':         'كلمة المرور يجب أن تكون ٦ أحرف على الأقل',
  'passwords_not_match':    'كلمتا المرور غير متطابقتين',
  'no_account_found':       'لم يتم العثور على حساب. يرجى التسجيل أولاً.',
  'invalid_credentials':    'بريد إلكتروني أو كلمة مرور غير صحيحة',
  'categories':             'الفئات',
  'categories_count':       'فئات',
  'add_category':           'إضافة فئة',
  'new_category':           'فئة جديدة',
  'edit_category':          'تعديل الفئة',
  'delete_category':        'حذف الفئة',
  'delete_category_confirm':'هل أنت متأكد من حذف',
  'delete_category_warning':'سيتم إلغاء تخصيص جميع منتجات هذه الفئة.',
  'no_categories_yet':      'لا توجد فئات بعد',
  'no_categories_desc':     'ابدأ بإنشاء أول فئة لمنتجاتك لتنظيم المخزون.',
  'add_first_category':     'إضافة أول فئة',
  'category_name_hint':     'مثال: إلكترونيات، بقالة...',
  'choose_emoji':           'اختر أيقونة',
  'choose_color':           'اختر لوناً',
  'create_category':        'إنشاء الفئة',
  'save_changes':           'حفظ التغييرات',
  'category_added':         'تم إنشاء الفئة بنجاح',
  'category_exists':        'فئة بهذا الاسم موجودة بالفعل',
  'duplicate':              'مكرر',
  'products_count':         'منتجات',
  'no_products_yet':        'لا توجد منتجات بعد',
  'setup_required':         'الإعداد مطلوب',
  'add_first_product_desc': 'أضف منتجك الأول لبدء إدارة المخزون.',
  'create_category_first_desc': 'يرجى إنشاء فئة واحدة على الأقل قبل إضافة المنتجات.',
  'create_category_first':  'يرجى إنشاء فئة أولاً',
  'go_to_categories':       'الذهاب إلى الفئات',
  'no_results':             'لا توجد منتجات تطابق بحثك',
  'add_product':            'إضافة منتج',
  'edit_product':           'تعديل المنتج',
  'product_added':          'تمت إضافة المنتج بنجاح',
  'product_updated':        'تم تحديث المنتج بنجاح',
  'delete_product':         'حذف المنتج',
  'delete_product_confirm': 'هل أنت متأكد من حذف',
  'basic_info':             'المعلومات الأساسية',
  'product_name':           'اسم المنتج',
  'product_name_hint':      'مثال: كوكاكولا 500 مل',
  'product_name_required':  'اسم المنتج مطلوب',
  'brand':                  'العلامة التجارية',
  'brand_hint':             'مثال: نستله، سامسونج...',
  'description':            'الوصف',
  'description_hint':       'وصف اختياري للمنتج',
  'category':               'الفئة',
  'pricing':                'التسعير',
  'selling_price':          'سعر البيع',
  'cost_price':             'سعر التكلفة',
  'price_required':         'سعر البيع مطلوب',
  'stock_info':             'معلومات المخزون',
  'initial_qty':            'الكمية الابتدائية',
  'low_stock_threshold':    'تنبيه المخزون المنخفض عند',
  'unit':                   'الوحدة',
  'additional_info':        'معلومات إضافية',
  'barcode':                'الباركود / SKU',
  'barcode_hint':           'امسح أو اكتب الباركود',
  'add_photo':              'إضافة صورة',
  'take_photo':             'التقاط صورة',
  'choose_gallery':         'اختيار من المعرض',
  'remove_photo':           'إزالة الصورة',
  'camera':                 'الكاميرا',
  'gallery':                'المعرض',
  'retake':                 'إعادة التقاط',
  'remove':                 'إزالة',
  'select_category_required': 'يرجى اختيار فئة',
  'no_categories_warning':  'لا توجد فئات. يرجى إنشاء فئة أولاً.',
  'notice':                 'تنبيه',
  'success':                'نجاح',
  'error':                  'خطأ',
  'delete':                 'حذف',
  'cancel':                 'إلغاء',
  'edit':                   'تعديل',
  'save':                   'حفظ',
  'all':                    'الكل',
  'total':                  'المجموع',
  'low':                    'منخفض',
  'out':                    'نفذ',
  'pcs':                    'قطعة',
  // Navigation
  'nav_dashboard': 'لوحة التحكم',
  'nav_products': 'المنتجات',
  'nav_sales': 'المبيعات',
  'nav_customers': 'العملاء',

  // Dashboard
  'today': 'اليوم',
  'total_sales': 'إجمالي المبيعات',
  'total_profit': 'إجمالي الربح',
  'total_orders': 'إجمالي الطلبات',
  'low_stock_items': 'منتجات منخفضة',
  'vs_yesterday': 'مقارنة بالأمس',
  'sales_overview': 'نظرة عامة على المبيعات',
  'this_week': 'هذا الأسبوع',
  'this_month': 'هذا الشهر',
  'recent_transactions': 'المعاملات الأخيرة',
  'view_all': 'عرض الكل',
  'paid': 'مدفوع',
  'pending': 'معلق',
  'cancelled': 'ملغى',

  // Days
  'mon': 'الإثنين',
  'tue': 'الثلاثاء',
  'wed': 'الأربعاء',
  'thu': 'الخميس',
  'fri': 'الجمعة',
  'sat': 'السبت',
  'sun': 'الأحد',

  // Products
  'products': 'المنتجات',
  'all_products': 'جميع المنتجات',
  'in_stock': 'متوفر',
  'low_stock': 'مخزون منخفض',
  'out_of_stock': 'نفذ المخزون',
  'search_products': 'ابحث عن منتجات...',
  'electronics': 'إلكترونيات',
  'furniture': 'أثاث',
  'stationery': 'قرطاسية',

  // Invoice
  'invoice': 'فاتورة',
  'bill_to': 'فاتورة إلى',
  'bill_from': 'فاتورة من',
  'items': 'المنتجات',
  'qty': 'الكمية',
  'price': 'السعر',
  'subtotal': 'المجموع الفرعي',
  'discount': 'خصم',
  'vat': 'ضريبة القيمة المضافة (5%)',
  'payment_info': 'معلومات الدفع',
  'payment_method': 'طريقة الدفع',
  'paid_amount': 'المبلغ المدفوع',
  'change': 'الباقي',
  'cash': 'نقداً',
  'download_pdf': 'تحميل PDF',
  'share_whatsapp': 'مشاركة عبر واتساب',
  'send_email': 'إرسال بريد إلكتروني',
  'walk_in_customer': 'عميل عابر',
  'dubai_uae': 'دبي، الإمارات',
  'trn_label': 'رقم ضريبي:',

  // Currency
  'currency': 'درهم',
  // Stock
  'add_stock':           'إضافة مخزون',
  'select_product':      'اختر المنتج',
  'quantity_to_add':     'الكمية المراد إضافتها',
  'current_stock':       'المخزون الحالي',
  'confirm_add_stock':   'تأكيد إضافة المخزون',
  'stock_added':         'تمت إضافة المخزون',
  'units_added':         'وحدة مضافة إلى',
  'note_optional':       'ملاحظة (اختياري)',
  'no_products_found':   'لا توجد منتجات',

  // POS
  'pos':                      'نقطة البيع',
  'search_add_product':       'ابحث عن منتج وأضفه...',
  'cart_empty':               'السلة فارغة',
  'search_to_add':            'ابحث عن منتج أعلاه لإضافته',
  'unit_price':               'سعر الوحدة',
  'vat_5':                    'ضريبة (5%)',
  'grand_total':              'الإجمالي الكلي',
  'customer_name_optional':   'اسم العميل (اختياري)',
  'generate_invoice':         'إنشاء فاتورة',
  'clear_cart':               'مسح السلة',
  'clear_cart_confirm':       'هل تريد مسح السلة؟',
  'clear':                    'مسح',
  'whatsapp':                 'واتساب',

  // Invoice language picker
  'invoice_language':    'لغة الفاتورة',
  'select_invoice_lang': 'اختر لغة الفاتورة',

  // Shared
  'saved':              'تم الحفظ',
  'saved_to_device':    'تم الحفظ على جهازك',
};
