// ============================================================
// FILE: lib/core/localization/en_us.dart
// ============================================================

const Map<String, String> enUs = {
  // App
  'app_name': 'ABC Trading Co.',
  'hello': 'Hello',
// Auth
  'welcome_back':           'Welcome Back',
  'login_subtitle':         'Sign in to manage your business',
  'register_subtitle':      'Set up your business account',
  'email':                  'Email',
  'email_hint':             'you@business.com',
  'password':               'Password',
  'password_hint':          'At least 6 characters',
  'confirm_password':       'Confirm Password',
  'confirm_password_hint':  'Re-enter your password',
  'login':                  'Sign In',
  'register':               'Create Account',
  'create_account':         'Create Account',
  'or':                     'or',
  'business_info':          'Business Information',
  'business_name':          'Business Name',
  'business_name_hint':     'e.g. Ahmed General Store',
  'owner_name':             'Owner Name',
  'owner_name_hint':        'Your full name',
  'contact_info':           'Contact Information',
  'phone':                  'Phone Number',
  'phone_hint':             '+971 50 000 0000',
  'security':               'Security',
  'business_name_required': 'Business name is required',
  'valid_email_required':   'Enter a valid email address',
  'password_required':      'Password is required',
  'password_min_6':         'Password must be at least 6 characters',
  'passwords_not_match':    'Passwords do not match',
  'no_account_found':       'No account found. Please register first.',
  'invalid_credentials':    'Invalid email or password',

  // Categories
  'categories':             'Categories',
  'categories_count':       'categories',
  'add_category':           'Add Category',
  'new_category':           'New Category',
  'edit_category':          'Edit Category',
  'delete_category':        'Delete Category',
  'delete_category_confirm':'Are you sure you want to delete',
  'delete_category_warning':'All products in this category will need reassignment.',
  'no_categories_yet':      'No Categories Yet',
  'no_categories_desc':     'Start by creating your first product category to organize your inventory.',
  'add_first_category':     'Add First Category',
  'category_name_hint':     'e.g. Electronics, Grocery...',
  'choose_emoji':           'Choose Icon',
  'choose_color':           'Choose Color',
  'create_category':        'Create Category',
  'save_changes':           'Save Changes',
  'category_added':         'Category created successfully',
  'category_exists':        'A category with this name already exists',
  'duplicate':              'Duplicate',
  'products_count':         'products',

  // Products
  'no_products_yet':        'No Products Yet',
  'setup_required':         'Setup Required',
  'add_first_product_desc': 'Add your first product to start managing your inventory.',
  'create_category_first_desc': 'Please create at least one category before adding products.',
  'create_category_first':  'Please create a category first',
  'go_to_categories':       'Go to Categories',
  'no_results':             'No products match your search',
  'add_product':            'Add Product',
  'edit_product':           'Edit Product',
  'product_added':          'Product added successfully',
  'product_updated':        'Product updated successfully',
  'delete_product':         'Delete Product',
  'delete_product_confirm': 'Are you sure you want to delete',
  'basic_info':             'Basic Information',
  'product_name':           'Product Name',
  'product_name_hint':      'e.g. Coca Cola 500ml',
  'product_name_required':  'Product name is required',
  'brand':                  'Brand',
  'brand_hint':             'e.g. Nestle, Samsung...',
  'description':            'Description',
  'description_hint':       'Optional product description',
  'category':               'Category',
  'pricing':                'Pricing',
  'selling_price':          'Selling Price',
  'cost_price':             'Cost Price',
  'price_required':         'Selling price is required',
  'stock_info':             'Stock Information',
  'initial_qty':            'Initial Quantity',
  'low_stock_threshold':    'Low Stock Alert at',
  'unit':                   'Unit',
  'additional_info':        'Additional Info',
  'barcode':                'Barcode / SKU',
  'barcode_hint':           'Scan or type barcode',
  'add_photo':              'Add Photo',
  'take_photo':             'Take Photo',
  'choose_gallery':         'Choose from Gallery',
  'remove_photo':           'Remove Photo',
  'camera':                 'Camera',
  'gallery':                'Gallery',
  'retake':                 'Retake',
  'remove':                 'Remove',
  'select_category_required': 'Please select a category',
  'no_categories_warning':  'No categories found. Please create a category first.',
  'notice':                 'Notice',

  // Shared
  'success':                'Success',
  'error':                  'Error',
  'delete':                 'Delete',
  'cancel':                 'Cancel',
  'edit':                   'Edit',
  'save':                   'Save',
  'all':                    'All',
  'total':                  'Total',
  'low':                    'Low',
  'out':                    'Out',
  'pcs':                    'pcs',
  // Navigation
  'nav_dashboard': 'Dashboard',
  'nav_products': 'Products',
  'nav_sales': 'Sales',
  'nav_customers': 'Customers',

  // Dashboard
  'today': 'Today',
  'total_sales': 'Total Sales',
  'total_profit': 'Total Profit',
  'total_orders': 'Total Orders',
  'low_stock_items': 'Low Stock Items',
  'vs_yesterday': 'vs yesterday',
  'sales_overview': 'Sales Overview',
  'this_week': 'This Week',
  'this_month': 'This Month',
  'recent_transactions': 'Recent Transactions',
  'view_all': 'View All',
  'paid': 'Paid',
  'pending': 'Pending',
  'cancelled': 'Cancelled',

  // Days
  'mon': 'Mon',
  'tue': 'Tue',
  'wed': 'Wed',
  'thu': 'Thu',
  'fri': 'Fri',
  'sat': 'Sat',
  'sun': 'Sun',

  // Products
  'products': 'Products',
  'all_products': 'All Products',
  'in_stock': 'In Stock',
  'low_stock': 'Low Stock',
  'out_of_stock': 'Out of Stock',
  'search_products': 'Search products...',
  'electronics': 'Electronics',
  'furniture': 'Furniture',
  'stationery': 'Stationery',

  // Invoice
  'invoice': 'Invoice',
  'bill_to': 'Bill To',
  'bill_from': 'Bill From',
  'items': 'Items',
  'qty': 'Qty',
  'price': 'Price',
  'subtotal': 'Subtotal',
  'discount': 'Discount',
  'vat': 'VAT (5%)',
  'payment_info': 'Payment Info',
  'payment_method': 'Method',
  'paid_amount': 'Paid Amount',
  'change': 'Change',
  'cash': 'Cash',
  'download_pdf': 'Download PDF',
  'share_whatsapp': 'Share via WhatsApp',
  'send_email': 'Send Email',
  'walk_in_customer': 'Walk-in Customer',
  'dubai_uae': 'Dubai, UAE',
  'trn_label': 'TRN:',

  // Currency
  'currency': 'AED',
  'add_stock':           'Add Stock',
  'select_product':      'Select Product',
  'quantity_to_add':     'Quantity to Add',
  'current_stock':       'Current Stock',
  'confirm_add_stock':   'Confirm Add Stock',
  'stock_added':         'Stock Added',
  'units_added':         'units added to',
  'note_optional':       'Note (Optional)',
  'no_products_found':   'No products found',

  // POS
  'pos':                      'Point of Sale',
  'search_add_product':       'Search and add product...',
  'cart_empty':               'Cart is Empty',
  'search_to_add':            'Search for a product above to add it to the cart',
  'unit_price':               'Unit Price',
  'vat_5':                    'VAT (5%)',
  'grand_total':              'Grand Total',
  'customer_name_optional':   'Customer name (optional)',
  'generate_invoice':         'Generate Invoice',
  'clear_cart':               'Clear Cart',
  'clear_cart_confirm':       'Are you sure you want to clear the cart?',
  'clear':                    'Clear',
  'whatsapp':                 'WhatsApp',

  // Invoice language picker
  'invoice_language':    'Invoice Language',
  'select_invoice_lang': 'Choose the language for the generated invoice',

  // Shared
  'saved':              'Saved',
  'saved_to_device':    'saved to your device',

};
