// ============================================================
// FILE: lib/core/localization/ur_pk.dart
// ============================================================

const Map<String, String> urPk = {
  // App
  'app_name': 'اے بی سی ٹریڈنگ کمپنی',
  'hello': 'ہیلو',
  'welcome_back':           'خوش آمدید',
  'login_subtitle':         'اپنا کاروبار منظم کرنے کے لیے سائن ان کریں',
  'register_subtitle':      'اپنا کاروباری اکاؤنٹ بنائیں',
  'email':                  'ای میل',
  'email_hint':             'آپ کی ای میل',
  'password':               'پاسورڈ',
  'password_hint':          'کم از کم 6 حروف',
  'confirm_password':       'پاسورڈ کی تصدیق',
  'confirm_password_hint':  'پاسورڈ دوبارہ درج کریں',
  'login':                  'سائن ان',
  'register':               'اکاؤنٹ بنائیں',
  'create_account':         'اکاؤنٹ بنائیں',
  'or':                     'یا',
  'business_info':          'کاروباری معلومات',
  'business_name':          'کاروبار کا نام',
  'business_name_hint':     'مثلاً احمد جنرل اسٹور',
  'owner_name':             'مالک کا نام',
  'owner_name_hint':        'آپ کا پورا نام',
  'contact_info':           'رابطہ معلومات',
  'phone':                  'فون نمبر',
  'phone_hint':             '+971 50 000 0000',
  'security':               'سیکیورٹی',
  'business_name_required': 'کاروبار کا نام ضروری ہے',
  'valid_email_required':   'درست ای میل درج کریں',
  'password_required':      'پاسورڈ ضروری ہے',
  'password_min_6':         'پاسورڈ کم از کم 6 حروف کا ہونا چاہیے',
  'passwords_not_match':    'پاسورڈ مطابقت نہیں کرتے',
  'no_account_found':       'کوئی اکاؤنٹ نہیں ملا۔ پہلے رجسٹر کریں۔',
  'invalid_credentials':    'غلط ای میل یا پاسورڈ',
  'categories':             'زمرہ جات',
  'categories_count':       'زمرہ جات',
  'add_category':           'زمرہ شامل کریں',
  'new_category':           'نیا زمرہ',
  'edit_category':          'زمرہ ترمیم کریں',
  'delete_category':        'زمرہ حذف کریں',
  'delete_category_confirm':'کیا آپ واقعی حذف کرنا چاہتے ہیں',
  'delete_category_warning':'اس زمرے کے تمام مصنوعات کو دوبارہ تفویض کرنا ہوگا۔',
  'no_categories_yet':      'ابھی کوئی زمرہ نہیں',
  'no_categories_desc':     'اپنا پہلا زمرہ بنائیں تاکہ انوینٹری منظم ہو سکے۔',
  'add_first_category':     'پہلا زمرہ شامل کریں',
  'category_name_hint':     'مثلاً الیکٹرونکس، گروسری...',
  'choose_emoji':           'آئیکن منتخب کریں',
  'choose_color':           'رنگ منتخب کریں',
  'create_category':        'زمرہ بنائیں',
  'save_changes':           'تبدیلیاں محفوظ کریں',
  'category_added':         'زمرہ کامیابی سے بنایا گیا',
  'category_exists':        'اس نام کا زمرہ پہلے سے موجود ہے',
  'duplicate':              'نقل',
  'products_count':         'مصنوعات',
  'no_products_yet':        'ابھی کوئی مصنوعہ نہیں',
  'setup_required':         'سیٹ اپ ضروری ہے',
  'add_first_product_desc': 'انوینٹری شروع کرنے کے لیے پہلا مصنوعہ شامل کریں۔',
  'create_category_first_desc': 'مصنوعات شامل کرنے سے پہلے کم از کم ایک زمرہ بنائیں۔',
  'create_category_first':  'پہلے ایک زمرہ بنائیں',
  'go_to_categories':       'زمرہ جات پر جائیں',
  'no_results':             'کوئی مصنوعہ نہیں ملا',
  'add_product':            'مصنوعہ شامل کریں',
  'edit_product':           'مصنوعہ ترمیم کریں',
  'product_added':          'مصنوعہ کامیابی سے شامل ہوا',
  'product_updated':        'مصنوعہ کامیابی سے اپڈیٹ ہوا',
  'delete_product':         'مصنوعہ حذف کریں',
  'delete_product_confirm': 'کیا آپ واقعی حذف کرنا چاہتے ہیں',
  'basic_info':             'بنیادی معلومات',
  'product_name':           'مصنوعے کا نام',
  'product_name_hint':      'مثلاً کوکا کولا 500ملی',
  'product_name_required':  'مصنوعے کا نام ضروری ہے',
  'brand':                  'برانڈ',
  'brand_hint':             'مثلاً نیسلے، سام سنگ...',
  'description':            'تفصیل',
  'description_hint':       'اختیاری تفصیل',
  'category':               'زمرہ',
  'pricing':                'قیمت',
  'selling_price':          'فروخت قیمت',
  'cost_price':             'لاگت قیمت',
  'price_required':         'قیمت ضروری ہے',
  'stock_info':             'اسٹاک معلومات',
  'initial_qty':            'ابتدائی مقدار',
  'low_stock_threshold':    'کم اسٹاک الرٹ',
  'unit':                   'اکائی',
  'additional_info':        'اضافی معلومات',
  'barcode':                'بارکوڈ / SKU',
  'barcode_hint':           'بارکوڈ اسکین یا ٹائپ کریں',
  'add_photo':              'تصویر شامل کریں',
  'take_photo':             'تصویر لیں',
  'choose_gallery':         'گیلری سے منتخب کریں',
  'remove_photo':           'تصویر ہٹائیں',
  'camera':                 'کیمرہ',
  'gallery':                'گیلری',
  'retake':                 'دوبارہ لیں',
  'remove':                 'ہٹائیں',
  'select_category_required': 'براہ کرم ایک زمرہ منتخب کریں',
  'no_categories_warning':  'کوئی زمرہ نہیں ملا۔ پہلے زمرہ بنائیں۔',
  'notice':                 'نوٹس',
  'success':                'کامیاب',
  'error':                  'خرابی',
  'delete':                 'حذف',
  'cancel':                 'منسوخ',
  'edit':                   'ترمیم',
  'save':                   'محفوظ',
  'all':                    'سب',
  'total':                  'کل',
  'low':                    'کم',
  'out':                    'ختم',
  'pcs':                    'عدد',
  // Navigation
  'nav_dashboard': 'ڈیش بورڈ',
  'nav_products': 'مصنوعات',
  'nav_sales': 'فروخت',
  'nav_customers': 'گاہک',

  // Dashboard
  'today': 'آج',
  'total_sales': 'کل فروخت',
  'total_profit': 'کل منافع',
  'total_orders': 'کل آرڈر',
  'low_stock_items': 'کم اسٹاک اشیاء',
  'vs_yesterday': 'کل کے مقابلے میں',
  'sales_overview': 'فروخت کا جائزہ',
  'this_week': 'اس ہفتے',
  'this_month': 'اس مہینے',
  'recent_transactions': 'حالیہ لین دین',
  'view_all': 'سب دیکھیں',
  'paid': 'ادا شدہ',
  'pending': 'زیر التواء',
  'cancelled': 'منسوخ',

  // Days
  'mon': 'سوموار',
  'tue': 'منگل',
  'wed': 'بدھ',
  'thu': 'جمعرات',
  'fri': 'جمعہ',
  'sat': 'ہفتہ',
  'sun': 'اتوار',

  // Products
  'products': 'مصنوعات',
  'all_products': 'تمام مصنوعات',
  'in_stock': 'اسٹاک میں',
  'low_stock': 'کم اسٹاک',
  'out_of_stock': 'اسٹاک ختم',
  'search_products': 'مصنوعات تلاش کریں...',
  'electronics': 'الیکٹرونکس',
  'furniture': 'فرنیچر',
  'stationery': 'سٹیشنری',

  // Invoice
  'invoice': 'رسید',
  'bill_to': 'بل بھیجنا',
  'bill_from': 'بل سے',
  'items': 'اشیاء',
  'qty': 'مقدار',
  'price': 'قیمت',
  'subtotal': 'ذیلی کل',
  'discount': 'رعایت',
  'vat': 'ویٹ (5%)',
  'payment_info': 'ادائیگی کی معلومات',
  'payment_method': 'ادائیگی کا طریقہ',
  'paid_amount': 'ادا شدہ رقم',
  'change': 'باقی رقم',
  'cash': 'نقد',
  'download_pdf': 'PDF ڈاؤن لوڈ کریں',
  'share_whatsapp': 'واٹس ایپ پر شیئر کریں',
  'send_email': 'ای میل بھیجیں',
  'walk_in_customer': 'واک ان گاہک',
  'dubai_uae': 'دبئی، متحدہ عرب امارات',
  'trn_label': 'ٹیکس نمبر:',

  // Currency
  'currency': 'AED',
  // Stock
  'add_stock':           'اسٹاک شامل کریں',
  'select_product':      'مصنوعہ منتخب کریں',
  'quantity_to_add':     'شامل کرنے کی مقدار',
  'current_stock':       'موجودہ اسٹاک',
  'confirm_add_stock':   'اسٹاک کی تصدیق کریں',
  'stock_added':         'اسٹاک شامل ہو گیا',
  'units_added':         'یونٹ شامل کیے',
  'note_optional':       'نوٹ (اختیاری)',
  'no_products_found':   'کوئی مصنوعہ نہیں ملا',

  // POS
  'pos':                      'پوائنٹ آف سیل',
  'search_add_product':       'مصنوعہ تلاش کریں...',
  'cart_empty':               'کارٹ خالی ہے',
  'search_to_add':            'مصنوعہ شامل کرنے کے لیے اوپر تلاش کریں',
  'unit_price':               'یونٹ قیمت',
  'vat_5':                    'ویٹ (5%)',
  'grand_total':              'کل رقم',
  'customer_name_optional':   'گاہک کا نام (اختیاری)',
  'generate_invoice':         'انوائس بنائیں',
  'clear_cart':               'کارٹ صاف کریں',
  'clear_cart_confirm':       'کیا آپ کارٹ صاف کرنا چاہتے ہیں؟',
  'clear':                    'صاف کریں',
  'whatsapp':                 'واٹس ایپ',

  // Invoice language picker
  'invoice_language':    'انوائس کی زبان',
  'select_invoice_lang': 'انوائس کے لیے زبان منتخب کریں',

  // Shared
  'saved':              'محفوظ',
  'saved_to_device':    'آپ کے ڈیوائس میں محفوظ',
};
